image: alpine/edge
packages:
  - crystal
  - shards
  - zlib-dev
  - openssl-dev
  - libcrypto1.1
sources:
  - https://git.sr.ht/~pixelinc/gmod-checker.cr
tasks:
  - format: |
      cd gmod-checker.cr
      crystal tool format --check
  - compile: |
      cd gmod-checker.cr
      shards build --no-codegen
  - spec: |
      cd gmod-checker.cr
      crystal spec
